<a href="<?=$this->url('users/add')?>" class='btn btn-primary'>
    <?=$this->translate('__add_user')?>
</a>
<br/>
<br/>

<table>
    <thead>
        <tr>
            <th>
                <a href="<?=$this->url('users', array('orderBy'   =>  'id'))?>"> <?=$this->translate('__user_id')?> </a>
            </th>
            <th>
               <!-- <a href="<?=$this->url('users', array('orderBy'   =>  'firstname'))?>"><?=$this->translate('__user_firstname')?> </a> -->
               <?=$this->translate('__user_firstname')?>
            </th>
            <th>
                <!-- <a href="<?=$this->url('users', array('orderBy'   =>  'lastname'))?>"><?=$this->translate('__user_lastname')?> </a>-->
               <?=$this->translate('__user_lastname')?>
            </th>
            <th>
                <a href="<?=$this->url('users', array('orderBy'   =>  'email'))?>"><?=$this->translate('__user_email')?> </a>
            </th>
            <th>
               <!--  <a href="<?=$this->url('users', array('orderBy'   =>  'address'))?>"><?=$this->translate('__user_address')?> </a> -->
               <?=$this->translate('__user_address')?>
            </th>
            <th>
                <!-- <a href="<?=$this->url('users', array('orderBy'   =>  'birthday'))?>"><?=$this->translate('__user_birthday')?> </a> -->
               <?=$this->translate('__user_birthday')?>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php
    /* @var $user \Application\Entity\User */
    foreach($this->users as $user)
    {
        ?>
        <tr>
        <td>
            <?=$user['id']?>
        </td>
        <td>
            <?=$user['profile']['firstname']?>
        </td>
        <td>
            <?=$user['profile']['lastname']?>
        </td>
        <td>
            <a href='mailto:<?=$user['email']?>'>
                <?=$user['email']?>
            </a>
        </td>
        <td>
            <?=$user['profile']['address']?>
        </td>
        <td>
            <?=$user->getBirthday()->format('d/m/Y')?>
        </td>
        <td>
            <a href="<?=$this->url('users/edit', array('user_id'   =>  $user['id']))?>" class="btn btn-success">
                <?=$this->translate('__edit_user')?>
            </a>
           <a href="<?=$this->url('users/remove', array('user_id'   =>  $user['id']))?>" class="btn btn-danger">
            <?=$this->translate('__remove_user')?>
           </a>
        </td>
        </tr>
        <?php
    }
    ?>
    </tbody>
</table>